# Generated by Django 2.0.2 on 2018-02-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('crn', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, verbose_name='CRN')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Subject')),
                ('course_id', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Course ID')),
                ('course_name', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Course Name')),
                ('units', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Units')),
                ('type', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Type')),
                ('days', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('hours', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('room', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('dates', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('instructor', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Instructor')),
                ('lecture_crn', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Lecture CRN')),
                ('term', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Term')),
                ('capacity', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Capacity')),
                ('enrolled', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Enrolled')),
                ('available', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Available')),
                ('final_type', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_days', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_hours', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_room', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_dates', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_type_2', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_days_2', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_hours_2', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_room_2', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('final_dates_2', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
