# Generated by Django 2.0.2 on 2018-02-20 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_discussion', to='course_api.Course', verbose_name='Associated Discussion'),
        ),
        migrations.AddField(
            model_name='course',
            name='discussion_crn',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Discussion CRN'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lecture', to='course_api.Course', verbose_name='Associated Lecture'),
        ),
    ]
