# Generated by Django 2.0.2 on 2018-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Course Name')),
                ('lectures', models.ManyToManyField(db_index=True, related_name='lectures', to='course_api.Course', verbose_name='Lectures')),
                ('other_classes', models.ManyToManyField(db_index=True, related_name='other_classes', to='course_api.Course', verbose_name='Other Classes')),
            ],
            options={
                'verbose_name': 'Subject Class',
                'verbose_name_plural': 'Subject Classes',
            },
        ),
    ]
