# Generated by Django 2.0.2 on 2018-02-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0005_auto_20180228_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectclass',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='subjectclass',
            name='other_classes',
        ),
    ]
