# Generated by Django 2.0.2 on 2018-03-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0006_auto_20180228_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='simple_name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Simple Name'),
        ),
    ]
