# Generated by Django 2.0.2 on 2018-03-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0009_auto_20180314_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.TextField(default='[]', verbose_name='Courses'),
        ),
    ]
