# Generated by Django 2.0.2 on 2018-03-22 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0010_auto_20180322_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(auto_created=True, db_index=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
