# Generated by Django 2.0.2 on 2018-03-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0012_auto_20180322_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcourse',
            name='course_subject',
            field=models.CharField(db_index=True, max_length=256, null=True, verbose_name='Course Subject'),
        ),
    ]
