# Generated by Django 2.0.2 on 2018-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0014_scheduleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/images'),
        ),
    ]
