# Generated by Django 2.0.3 on 2018-04-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0016_subjectcourse_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discussion_crn',
            new_name='attached_crn',
        ),
    ]
