# Generated by Django 2.0.3 on 2018-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0017_auto_20180404_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='important',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Important'),
        ),
        migrations.AlterField(
            model_name='course',
            name='attached_crn',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Attached CRN'),
        ),
    ]
