# Generated by Django 2.0.3 on 2018-04-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0018_auto_20180411_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='linked_courses',
            field=models.TextField(default='[]', verbose_name='Linked Courses'),
        ),
    ]
