# Generated by Django 2.0.3 on 2018-05-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0019_course_linked_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectClass',
        ),
    ]
