# Generated by Django 2.0.3 on 2018-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0020_delete_subjectclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('terms', models.TextField(default='[]', verbose_name='Terms')),
                ('school', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='School')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
