# Generated by Django 2.0.3 on 2018-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0021_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='School')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Term', 'verbose_name_plural': 'Terms'},
        ),
    ]
