# Generated by Django 2.0.3 on 2018-05-18 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_api', '0023_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=64, verbose_name='Course')),
                ('course', models.CharField(max_length=64, verbose_name='Course')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Subscribed Users')),
            ],
            options={
                'verbose_name': 'Waitlist',
                'verbose_name_plural': 'Waitlists',
            },
        ),
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('school', 'course')},
        ),
    ]
