# Generated by Django 2.0.3 on 2018-05-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0024_auto_20180517_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_api.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='school',
            field=models.CharField(max_length=64, verbose_name='School'),
        ),
    ]
