# Generated by Django 2.0.3 on 2018-05-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0025_auto_20180517_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
    ]
