# Generated by Django 2.1.2 on 2018-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0029_auto_20181024_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedules_generated', models.IntegerField(db_index=True, verbose_name='Schedules Generated')),
            ],
        ),
    ]
